"use strict";

/**
 * GAME BRAIN KNOWLEDGE — ACCOUNT STATS METADATA v4.11z52m
 * These are metadata names only. They help future Knowledge Base/History planning; they are not live account values.
 */

export const ACCOUNT_STATS_METADATA_KNOWLEDGE = Object.freeze([
    Object.freeze({
        id: "account-stat:Year",
        term: "Year",
        type: "Account stat metadata",
        family: "Account Stats / Other",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: Year.",
        aliases: Object.freeze(["Year"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:TournamentPromotionsAmount",
        term: "Tournament Promotions Amount",
        type: "Account stat metadata",
        family: "Account Stats / Tournament",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: TournamentPromotionsAmount.",
        aliases: Object.freeze(["TournamentPromotionsAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:TournamentDemotionsAmount",
        term: "Tournament Demotions Amount",
        type: "Account stat metadata",
        family: "Account Stats / Tournament",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: TournamentDemotionsAmount.",
        aliases: Object.freeze(["TournamentDemotionsAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:TournamentHighestLeague",
        term: "Tournament Highest League",
        type: "Account stat metadata",
        family: "Account Stats / Tournament",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: TournamentHighestLeague.",
        aliases: Object.freeze(["TournamentHighestLeague"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ChainLightningAmount",
        term: "Chain Lightning Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ChainLightningAmount.",
        aliases: Object.freeze(["ChainLightningAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:SmartMissilesAmount",
        term: "Smart Missiles Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: SmartMissilesAmount.",
        aliases: Object.freeze(["SmartMissilesAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:SmartMissilsDamage",
        term: "Smart Missiles Damage",
        type: "Account stat metadata",
        family: "Account Stats / Other",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: SmartMissilsDamage.",
        aliases: Object.freeze(["SmartMissilsDamage"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DeathWaveAmount",
        term: "Death Wave Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DeathWaveAmount.",
        aliases: Object.freeze(["DeathWaveAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ChronoFieldAmount",
        term: "Chrono Field Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ChronoFieldAmount.",
        aliases: Object.freeze(["ChronoFieldAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ChronoFieldDuration",
        term: "Chrono Field Duration",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ChronoFieldDuration.",
        aliases: Object.freeze(["ChronoFieldDuration"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:InnerLandMinesDamage",
        term: "Inner Land Mines Damage",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: InnerLandMinesDamage.",
        aliases: Object.freeze(["InnerLandMinesDamage"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:InnerLandMinesAmount",
        term: "Inner Land Mines Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: InnerLandMinesAmount.",
        aliases: Object.freeze(["InnerLandMinesAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GoldenTowerCashAmount",
        term: "Golden Tower Cash Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GoldenTowerCashAmount.",
        aliases: Object.freeze(["GoldenTowerCashAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GoldenTowerCoinAmount",
        term: "Golden Tower Coin Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GoldenTowerCoinAmount.",
        aliases: Object.freeze(["GoldenTowerCoinAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GoldenTowerDuration",
        term: "Golden Tower Duration",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GoldenTowerDuration.",
        aliases: Object.freeze(["GoldenTowerDuration"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:PoisonSwampDamage",
        term: "Poison Swamp Damage",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: PoisonSwampDamage.",
        aliases: Object.freeze(["PoisonSwampDamage"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:PoisonSwampAmount",
        term: "Poison Swamp Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: PoisonSwampAmount.",
        aliases: Object.freeze(["PoisonSwampAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:BlackHoleAmount",
        term: "Black Hole Amount",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: BlackHoleAmount.",
        aliases: Object.freeze(["BlackHoleAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:BlackHoleAffected",
        term: "Black Hole Affected",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: BlackHoleAffected.",
        aliases: Object.freeze(["BlackHoleAffected"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:SpotlightDamage",
        term: "Spotlight Damage",
        type: "Account stat metadata",
        family: "Account Stats / Ultimate Weapons",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: SpotlightDamage.",
        aliases: Object.freeze(["SpotlightDamage"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ModulesBoughtAmount",
        term: "Modules Bought Amount",
        type: "Account stat metadata",
        family: "Account Stats / Modules",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ModulesBoughtAmount.",
        aliases: Object.freeze(["ModulesBoughtAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ModulesEarnedAmount",
        term: "Modules Earned Amount",
        type: "Account stat metadata",
        family: "Account Stats / Modules",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ModulesEarnedAmount.",
        aliases: Object.freeze(["ModulesEarnedAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:ModulesShattered",
        term: "Modules Shattered",
        type: "Account stat metadata",
        family: "Account Stats / Modules",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: ModulesShattered.",
        aliases: Object.freeze(["ModulesShattered"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToBasic",
        term: "Died To Basic",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToBasic.",
        aliases: Object.freeze(["DiedToBasic"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToFast",
        term: "Died To Fast",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToFast.",
        aliases: Object.freeze(["DiedToFast"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToRanged",
        term: "Died To Ranged",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToRanged.",
        aliases: Object.freeze(["DiedToRanged"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToTank",
        term: "Died To Tank",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToTank.",
        aliases: Object.freeze(["DiedToTank"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToProtector",
        term: "Died To Protector",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToProtector.",
        aliases: Object.freeze(["DiedToProtector"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToBoss",
        term: "Died To Boss",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToBoss.",
        aliases: Object.freeze(["DiedToBoss"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToVampire",
        term: "Died To Vampire",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToVampire.",
        aliases: Object.freeze(["DiedToVampire"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToRay",
        term: "Died To Ray",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToRay.",
        aliases: Object.freeze(["DiedToRay"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToScatterMain",
        term: "Died To Scatter Main",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToScatterMain.",
        aliases: Object.freeze(["DiedToScatterMain"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToScatterChild",
        term: "Died To Scatter Child",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToScatterChild.",
        aliases: Object.freeze(["DiedToScatterChild"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToSaboteur",
        term: "Died To Saboteur",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToSaboteur.",
        aliases: Object.freeze(["DiedToSaboteur"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToCommander",
        term: "Died To Commander",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToCommander.",
        aliases: Object.freeze(["DiedToCommander"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DiedToOvercharge",
        term: "Died To Overcharge",
        type: "Account stat metadata",
        family: "Account Stats / Death Causes",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DiedToOvercharge.",
        aliases: Object.freeze(["DiedToOvercharge"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledBasic",
        term: "Killed Basic",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledBasic.",
        aliases: Object.freeze(["KilledBasic"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledFast",
        term: "Killed Fast",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledFast.",
        aliases: Object.freeze(["KilledFast"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledRanged",
        term: "Killed Ranged",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledRanged.",
        aliases: Object.freeze(["KilledRanged"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledTank",
        term: "Killed Tank",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledTank.",
        aliases: Object.freeze(["KilledTank"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledProtector",
        term: "Killed Protector",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledProtector.",
        aliases: Object.freeze(["KilledProtector"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledBoss",
        term: "Killed Boss",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledBoss.",
        aliases: Object.freeze(["KilledBoss"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledVampire",
        term: "Killed Vampire",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledVampire.",
        aliases: Object.freeze(["KilledVampire"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledRay",
        term: "Killed Ray",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledRay.",
        aliases: Object.freeze(["KilledRay"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledScatterMain",
        term: "Killed Scatter Main",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledScatterMain.",
        aliases: Object.freeze(["KilledScatterMain"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledScatterChild",
        term: "Killed Scatter Child",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledScatterChild.",
        aliases: Object.freeze(["KilledScatterChild"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledSaboteur",
        term: "Killed Saboteur",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledSaboteur.",
        aliases: Object.freeze(["KilledSaboteur"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledCommander",
        term: "Killed Commander",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledCommander.",
        aliases: Object.freeze(["KilledCommander"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:KilledOvercharge",
        term: "Killed Overcharge",
        type: "Account stat metadata",
        family: "Account Stats / Enemy Kills",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: KilledOvercharge.",
        aliases: Object.freeze(["KilledOvercharge"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameBattlesStarted",
        term: "Game Battles Started",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameBattlesStarted.",
        aliases: Object.freeze(["GameBattlesStarted"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameBattlesSurrendered",
        term: "Game Battles Surrendered",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameBattlesSurrendered.",
        aliases: Object.freeze(["GameBattlesSurrendered"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameWavesSkippedCard",
        term: "Game Waves Skipped Card",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameWavesSkippedCard.",
        aliases: Object.freeze(["GameWavesSkippedCard"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameWavesSkippedIS",
        term: "Game Waves Skipped I S",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameWavesSkippedIS.",
        aliases: Object.freeze(["GameWavesSkippedIS"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameWavesCleared",
        term: "Game Waves Cleared",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameWavesCleared.",
        aliases: Object.freeze(["GameWavesCleared"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameTimeInBattle",
        term: "Game Time In Battle",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameTimeInBattle.",
        aliases: Object.freeze(["GameTimeInBattle"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameDeathDefyAmount",
        term: "Game Death Defy Amount",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameDeathDefyAmount.",
        aliases: Object.freeze(["GameDeathDefyAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameSecondWindAmount",
        term: "Game Second Wind Amount",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameSecondWindAmount.",
        aliases: Object.freeze(["GameSecondWindAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameDemonModeAmount",
        term: "Game Demon Mode Amount",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameDemonModeAmount.",
        aliases: Object.freeze(["GameDemonModeAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:GameDemonModeDuration",
        term: "Game Demon Mode Duration",
        type: "Account stat metadata",
        family: "Account Stats / Lifetime Battle Totals",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: GameDemonModeDuration.",
        aliases: Object.freeze(["GameDemonModeDuration"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:DailyMissionsCompleted",
        term: "Daily Missions Completed",
        type: "Account stat metadata",
        family: "Account Stats / Missions and Cards",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: DailyMissionsCompleted.",
        aliases: Object.freeze(["DailyMissionsCompleted"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:EventMissionsCompleted",
        term: "Event Missions Completed",
        type: "Account stat metadata",
        family: "Account Stats / Missions and Cards",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: EventMissionsCompleted.",
        aliases: Object.freeze(["EventMissionsCompleted"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
    Object.freeze({
        id: "account-stat:CardsPulledAmount",
        term: "Cards Pulled Amount",
        type: "Account stat metadata",
        family: "Account Stats / Missions and Cards",
        section: "Account Stats",
        sourceConfidence: "game-file-confirmed-metadata-name",
        summary: "Metadata field visible in TowerWrappedStats: CardsPulledAmount.",
        aliases: Object.freeze(["CardsPulledAmount"]),
        uses: Object.freeze(["future account stats", "Systems knowledge base", "History planning"]),
        source: "v28.2.0 TowerWrappedStats IL2CPP metadata names",
        caution: "Metadata name only; not a live value and not a hidden formula."
    }),
]);

export function getAccountStatsMetadataKnowledge() {
    return ACCOUNT_STATS_METADATA_KNOWLEDGE;
}
